### ISSUE TITLE
Finish v2

### ISSUE THREAD

**Issue by FlorianFranzen** [kvoit/TeensyCamController#1]
## ToDo
- [x] ESD-safe trigger
- [x] 56V-safe pads on LDD
- [x] Add RSpro BNC footprint
